// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/osenv.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class OsenvBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OsenvBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OsenvBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Char> get_env(ffi.Pointer<ffi.Char> name) {
    return _get_env(name);
  }

  late final _get_envPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('get_env');
  late final _get_env = _get_envPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int set_env(ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> value) {
    return _set_env(name, value);
  }

  late final _set_envPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('set_env');
  late final _set_env = _set_envPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int unset_env(ffi.Pointer<ffi.Char> name) {
    return _unset_env(name);
  }

  late final _unset_envPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'unset_env',
      );
  late final _unset_env = _unset_envPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();
}
